language: python

cache: pip

python:
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - pip install coveralls
    - pip install codecov
    - pip install -r website/REQUIREMENTS.txt
    - pip install .
    - git clone https://github.com/MISP/misp-taxonomies.git

script:
    - nosetests --with-coverage --cover-package=pytaxonomies -d

after_success:
    - codecov
    - coveralls
