language: python

cache: pip

python:
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"
    - "3.8"
    - "3.8-dev"
    - "3.9"
    - "3.9-dev"

install:
    - pip install poetry
    - poetry install -E webui -E remote

script:
    - poetry run nosetests-3.4 --with-coverage --cover-package=pytaxonomies -d
    - poetry run mypy pytaxonomies

after_success:
    - poetry run codecov
    - poetry run coveralls
